services:
  my-sql:
    build: ../core-mysql
    image: core-my-sql-i
    container_name: core-my-sql-c
    volumes:
      - ../core-mysql/volume:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ../core-mysql/.env
    restart: unless-stopped

  php-myadmin:
    build: ../core-phpmyadmin
    image: core-php-myadmin-i
    container_name: core-php-myadmin-c
    env_file:
      - ../core-phpmyadmin/.env
    ports:
      - 3310:80
    restart: unless-stopped

  db-init-mysql:
    build: ../core-database-initializer-alpine-mysql-client
    image: core-db-init-mysql-i
    container_name: core-db-init-mysql-c
    env_file:
      - ../core-database-initializer-alpine-mysql-client/.env

  backend:
    build: ../core-java-spring-boot-rest-api
    image: core-backend-i
    container_name: core-backend-c
    ports:
      - 8080:80
    restart: unless-stopped

  portainer:
    build: ../core-portainer
    image: core-portainer-i
    container_name: core-portainer-c
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../core-portainer/mount:/data
    restart: unless-stopped